### ISSUE TITLE
Is this comment correct?

### ISSUE THREAD

**Issue by taylor13** [ESGF/esgf-compute-api#49]
In the "getting started" example, near the end it says: "Here we'll execute the process on the server. We're using the inputs and domain we defined above and applying regridding to grid T21.".  Where in the coding does it specify the destination grid?

**Comment by doutriaux1** [comment]
@taylor13 I think you're right in the getting started (https://github.com/ESGF/esgf-compute-api/blob/devel/examples/getting_started.ipynb) we are not regridding at all.

**Comment by taylor13** [comment]
No need to include regridding in this example, so can fix the problem by remove from the comment: "and applying regridding to grid T21."

**Comment by jasonb5** [comment]
Ah yes the example originally had regridding but I had removed it.

I'll remove the comment from the documentation.

**Comment by jasonb5** [comment]
Fixed in https://github.com/ESGF/esgf-compute-api/commit/853de0ce17a544e5c2c18888fbd5b9c51cfbbf0a.
