### ISSUE TITLE
Subset and download file.

### ISSUE THREAD

**Issue by taylor13** [ESGF/esgf-compute-api#50]
A common use case will be to subset and/or aggregate the data, then write the result to a netcdf file identical to the original except for the domain, dimensions, and a few variable and dimension attributes.  The global attributes should be identical to those in the files from which the subset was extracted.  Could you write an example of how this could be done?

**Comment by doutriaux1** [comment]
@jasonb5 in the getting started let's use two files rather than one.

**Comment by taylor13** [comment]
And I think users will want to either concatenate the two files after subsetting, or download two files with all the original metadata but only the subset of data itself.

**Comment by jasonb5** [comment]
@doutriaux1 so we want the getting started to be an aggregation with subset? 

There might also be another issue here. Currently the output is a cwt.Variable that points to an OpenDAP url with a file containing the result data and original metadata. But other than opening it with CDMS2 or some similar library that supports OpenDAP there's no other way to localize the file. 

I'm thinking a simple solution to this would be enabling THREDDS as a file server as well and providing two output links; OpenDAP and FileServer. I'll have to adjust the end-user API to support multiple outputs.

**Comment by taylor13** [comment]
I don't think it is essential that it be the "featured" getting started script, but it certainly should be one of the examples.  We might later choose to feature it.

**Comment by taylor13** [comment]
I don't think it is essential that it be the "featured" getting started script, but it certainly should be one of the examples.  We might later choose to feature it.

**Comment by jasonb5** [comment]
We have a few examples i'll need to add a gallery with descriptions and make it more accessible.

**Comment by taylor13** [comment]
And I think users will want to either concatenate the two files after subsetting, or download two files with all the original metadata but only the subset of data itself.

**Comment by lee1043** [comment]
I second @taylor13. One example would be loading multiple daily nc files and using them in one time model, just like loading a xml file that indices multiple nc files of same variable from same model.

**Comment by doutriaux1** [comment]
@taylor13 @lee1043 isn't this exactly what is described here: https://github.com/ESGF/esgf-compute-api/blob/devel/examples/aggregate_subset.ipynb

**Comment by lee1043** [comment]
@doutriaux1 good to know. Yes. Thanks!
