### ISSUE TITLE
Process failed to access file

### ISSUE THREAD

**Issue by davidcaron** [ESGF/esgf-compute-api#54]
Hi, I'm getting an error I never got before when running a process... And this process worked in the past using what I believe to be the same configuration. I'm following the exact notebook in `examples/aggregate.ipynb` and I get an error message. My token should be valid, I tried regenerating it also.

Here is the traceback:

```
ProcessAccepted Job accepted
ProcessStarted Job Started 6
Traceback (most recent call last):
  File "/c/projects/esgf-compute-api/sandbox.py", line 108, in <module>
    test_aggregate()
  File "/c/projects/esgf-compute-api/sandbox.py", line 51, in test_aggregate
    print(agg.wait())
  File "/c/projects/esgf-compute-api/cwt/process.py", line 281, in wait
    update_history(self.status)
  File "/c/projects/esgf-compute-api/cwt/process.py", line 230, in status
    raise cwt.WPSError('ProcessFailed {}'.format(self.exception_message))
cwt.errors.WPSError: ProcessFailed Failed to access file 'http://aims3.llnl.gov/thredds/dodsC/cmip5_css02_data/cmip5/output1/CMCC/CMCC-CM/decadal2005/mon/atmos/Amon/r1i2p1/tas/1/tas_Amon_CMCC-CM_decadal2005_r1i2p1_200511-201512.nc'
```

Any ideas? Thanks!

**Comment by tomLandry** [comment]
Didn't we had a similar problem and it was changed by changing URL to /Fileserver instead of /dodsC ? Can't point out where exactly though.

**Comment by davidcaron** [comment]
It's different here, the processing function does need the dodsC url. It looks like the access error is happening server side, but I'm not sure.

By the way, I'm using the master branch.

**Comment by jasonb5** [comment]
@davidcaron I just tried to reproduce this and was unable to. There's a known intermittent issue with accessing data that I've been looking into and this may just be an example of that. Could you try running it again?

**Comment by davidcaron** [comment]
@jasonb5 You're right, it looks intermittent, it works now... I don't remember for how long it was down, but it seemed like an hour.
