### ISSUE TITLE
DescribeProcess on https://aims2.llnl.gov/wps

### ISSUE THREAD

**Issue by davidcaron** [ESGF/esgf-compute-api#55]
Not sure where to post this issue, so I'm leaving it here... 

When I do a describe process on aims2, I think there is an error in the returned schema.

Where we have: 
`ProcessDescription -> DataInputs -> Input -> ComplexOutput`
I think we should have:
`ProcessDescription -> DataInputs -> Input -> ComplexData`

https://aims2.llnl.gov/wps/?request=DescribeProcess&service=WPS&identifier=CDAT.subset

**Comment by jasonb5** [comment]
@davidcaron Nice catch, I'm going to move this over to esgf-compute-wps as it s a server bug. ESGF/esgf-compute-wps#200
