### ISSUE TITLE
Docker image jasonb87/cwt_api:devel do not exist anymore

### ISSUE THREAD

**Issue by tlvu** [ESGF/esgf-compute-api#58]
Was following https://github.com/ESGF/esgf-compute-api/blob/devel/docs/source/cwt_docker.md
```
docker run -d -p 9999:9999 jasonb87/cwt_api:devel

# After running the image open http://127.0.0.1:9999, the password is "esgf".
```
But the image is not available from docker hub
```
$ docker pull jasonb87/cwt_api:devel
Error response from daemon: pull access denied for jasonb87/cwt_api, repository does not exist or may require 'docker login'
```

**Comment by jasonb5** [comment]
@tlvu The documentation was out of date, it's been updated [here](https://github.com/ESGF/esgf-compute-api/tree/master#docker-image). Please note that the Docker image name has changed.

**Comment by tlvu** [comment]
I found out how to install all the packages needed from the Getting Started notebooks so I was able to configure our Jupyter env here https://mybinder.org/v2/gh/Ouranosinc/PAVICS-e2e-workflow-tests/master.  Thanks for the update.  Closing this issue.
