### ISSUE TITLE
Feedback on notebooks

### ISSUE THREAD

**Issue by huard** [ESGF/esgf-compute-api#59]
With master branch. 
Code does not work with Python 3

## getting started
- Step 3 : bad link to aims2 
- execute fails with 
```
---------------------------------------------------------------------------
WPSExceptionError                         Traceback (most recent call last)
<ipython-input-6-b84dd0a9047b> in <module>()
----> 1 wps.execute(proc, [tas], d0)

/home/david/.conda/envs/esgf/lib/python2.7/site-packages/cwt/wps_client.pyc in execute(self, process, inputs, domain, method, block, **kwargs)
    259             data = wps.execute(process.identifier, '1.0.0', [variables, domains, operation]).toxml(bds=bds)
    260 
--> 261             response = self.request(method, data=data)
    262         else:
    263             raise cwt.WPSError('{} method is unsupported'.format(method))

/home/david/.conda/envs/esgf/lib/python2.7/site-packages/cwt/wps_client.pyc in request(self, method, params, data)
    315 
    316         if isinstance(data, cwt.wps.ows.CTD_ANON_9):
--> 317             raise cwt.WPSExceptionError.from_binding(data)
    318 
    319         return data

WPSExceptionError: Code: NoApplicableCode Message: Invalid XML missing ComplexData element
```
with devel branch
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-99a6b9f362f5> in <module>()
----> 1 proc = client.process_by_name('CDAT.subset')

AttributeError: 'WPSClient' object has no attribute 'process_by_name'
```

**Comment by huard** [comment]
If I get the `proc` using client.processes()[2] instead, I get the same WPSExceptionError as above.

**Comment by jasonb5** [comment]
@huard The master branch was not up to date with the server version. I've synced the branch so you should be able to update and re-run everything. If you want to install from conda, version 2.2.0 is built from the master branch.

**Comment by tlvu** [comment]
@huard With the current Jupyter env deployed on our PAVICS, I was able to execute that Getting Started notebooks https://pavics.ouranos.ca/jupyter/user/public/lab/tree/tutorial-notebooks/esgf-compute-api-examples-devel/getting_started.ipynb but I am getting `WPSClientError: Client error 'Missing API key for WPS execute request'` even with the token you gave me so maybe the token has expired?

**Comment by huard** [comment]
Yes, will send you the updated token by mail.
