### ISSUE TITLE
ESGF search  API issue 

### ISSUE THREAD

**Issue by maheshguru** [ESGF/esgf-compute-api#6]
Dear team,

I'm using ESGF API for listing the files. I gave the parameters as input in given below
Project: Cordex
Institute: MPI-CSI
Time Freq: day
Ensemble: r1i1p1
Domain: WAS-44i
Driving Model: MPI-M-MPI-ESM-LR
OpenID: <my openid>
Password: <password>
esgf-node: https://esgf-node.ipsl.upmc.fr/esg-search

I'm getting error like

 "NetCDF: Access failure: http://esg-cccr.tropmet.res.in/thredds/dodsC/esg_dataroot1/cordex_noncommercial/cordex/output/WAS-44/IITM/CCCma-CanESM2/historical/r1i1p1/IITM-RegCM4-4/v5/day/pr/v20160824/pr_WAS-44_CCCma-CanESM2_historical_r1i1p1_IITM-RegCM4-4_v5_day_19510101-19551231.nc"

In above error, It shows the esgf node "http://esg-cccr.tropmet.res.in" and driving model "CCCma-CanESM2" instead of input datanode and driving model. But few days before, It was working fine.

I would like you to help me to solve this issue.

Thank you.

**Comment by sashakames** [comment]
Dear user "maheshguru"  - this issue isn't appropriate for this repo.  Please email:  esgf-user@llnl.gov for user support.

Thanks and best regards
