### ISSUE TITLE
Tweak notebooks to that the token is drawn from an environment variable 

### ISSUE THREAD

**Issue by huard** [ESGF/esgf-compute-api#60]
For our automated testing, it would help if the ESGF token was taken from an environment variable. This would let us set it without doing a regexp in the notebooks. 

That is, replace `api_key = 'TOKEN'` by

```
import os
api_key = os.environ.get('ESGF_AUTH_TOKEN', '<your token>')
```

**Comment by jasonb5** [comment]
63c067495e400a851829bb3be25d4cf842168926 changes the WPSClient to use either api_key/compute_token in the constructor or COMPUTE_TOKEN environment variable. We'll be deprecating api_key for compute_token. I've updated the notebooks which have `compute_token=None` this will cause the WPSClient to load from the COMPUTE_TOKEN environment variable if it's defined.

**Comment by jasonb5** [comment]
Uploaded 2.2.1 to conda.
