### ISSUE TITLE
Jupyter notebook installation in getting started instruction?

### ISSUE THREAD

**Issue by lee1043** [ESGF/esgf-compute-api#61]
The conda env generated following the instruction from the [example notebook](https://github.com/ESGF/esgf-compute-api/blob/master/examples/getting_started.ipynb) may not have the jupyter notebook.

For users those who are not familiar, I think it may not a bad idea to include `conda install jupyter` in the instruction. What do you think?

**Comment by jasonb5** [comment]
@lee1043 This is good idea, I will add some instructions on setting up a basic environment with jupyter.

**Comment by jasonb5** [comment]
Added some instructions for installing and running jupyterlab.
